services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=lmsdb'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=user'
    ports:
      - '5432'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
